name: Feature Request
description: Have a new idea/feature? Please suggest!
labels: enhancement
title: 'feat: <description>'
body:
- type: dropdown
  id: cli-or-crate
  attributes:
    label: Part
    description: Which sub-part of LTRS is it related to?
    options:
    - Executable (CLI)
    - Library (crate)
    - Both
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Description
    description: A brief description of the enhancement you propose, also include what you tried and what worked.
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: Please add screenshots if applicable
  validations:
    required: false
- type: textarea
  id: extrainfo
  attributes:
    label: Additional information
    description: Is there anything else we should know about this idea?
  validations:
    required: false
